### Get all emails
GET http://localhost:5000/emails
Accept: application/json

### Create a new email
POST http://localhost:5000/api/fetch-emails
Content-Type: application/json

{
  "to": "yourgmail@gmail.com",
  "subject": "Hello",
  "text": "This is a test email"
}


